using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Axion.Tokens {
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TokenType {
        Unknown,
        Invalid,

        Operator,
        Identifier,

        // TODO resolve literals
        CommentLiteral,
        CharLiteral,
        StringLiteral,
        ByteLiteral,
        Int16Literal,
        Int32Literal,
        Int64Literal,
        RealLiteral,
        DecimalLiteral,

        OpLeftParenthesis    = 40,
        OpRightParenthesis   = 41,
        OpLeftBracket        = 42,
        OpRightBracket       = 43,
        OpLeftBrace          = 44,
        OpRightBrace         = 45,
        OpDot                = 46,
        OpIncrement          = 47,
        OpDecrement          = 48,
        OpNot                = 49,
        OpBitwiseNot         = 50,
        OpMultiply           = 51,
        OpTrueDivide         = 52,
        OpRemainder          = 53,
        OpAdd                = 54,
        OpSubtract           = 55,
        OpLeftShift          = 56,
        OpRightShift         = 57,
        OpIn                 = 58,
        OpLessThan           = 59,
        OpLessThanOrEqual    = 60,
        OpGreaterThan        = 61,
        OpGreaterThanOrEqual = 62,
        OpEquals             = 63,
        OpNotEquals          = 64,
        OpBitwiseAnd         = 65,
        OpExclusiveOr        = 66,
        OpBitwiseOr          = 67,
        OpAnd                = 68,
        OpOr                 = 69,
        OpAssign             = 70,
        OpAddEqual           = 71,
        OpSubtractEqual      = 72,
        OpMultiplyEqual      = 73,
        OpTrueDivideEqual    = 74,
        OpRemainderEqual     = 75,
        OpLeftShiftEqual     = 76,
        OpRightShiftEqual    = 77,
        OpBitwiseAndEqual    = 78,
        OpBitwiseOrEqual     = 79,
        OpExclusiveOrEqual   = 80,
        OpRightArrow         = 81,
        OpComma              = 82,
        OpColon              = 83,

        FirstKeyword    = KeywordAnd,
        LastKeyword     = KeywordFalse,
        KeywordAnd      = 84,
        KeywordAnyway   = 85,
        KeywordAs       = 86,
        KeywordAssert   = 87,
        KeywordAsync    = 88,
        KeywordAwait    = 89,
        KeywordBreak    = 90,
        KeywordCase     = 91,
        KeywordCatch    = 92,
        KeywordClass    = 93,
        KeywordConst    = 94,
        KeywordContinue = 95,
        KeywordDefault  = 96,
        KeywordDo       = 97,
        KeywordElif     = 98,
        KeywordElse     = 99,
        KeywordEnum     = 100,
        KeywordExtends  = 101,
        KeywordFalse    = 102,
        KeywordFor      = 103,
        KeywordIf       = 104,
        KeywordIn       = 105,
        KeywordInner    = 106,
        KeywordIs       = 107,
        KeywordMatch    = 108,
        KeywordModule   = 109,
        KeywordNew      = 110,
        KeywordNull     = 111,
        KeywordOr       = 112,
        KeywordPrivate  = 113,
        KeywordPublic   = 114,
        KeywordReact    = 115,
        KeywordReadonly = 116,
        KeywordReturn   = 117,
        KeywordSelf     = 118,
        KeywordStatic   = 119,
        KeywordStruct   = 120,
        KeywordThrow    = 121,
        KeywordTrue     = 122,
        KeywordTry      = 123,
        KeywordUse      = 124,
        KeywordVar      = 125,
        KeywordWhile    = 126,
        KeywordYield    = 127,

        Newline,
        Indent,
        Outdent,
        EndOfFile
    }
}