from aenum import AutoNumberEnum, unique


@unique
class ProcessingOptions(AutoNumberEnum):
    default = 0
    """ Source is processed by default.
    """

    check_indentation_consistency = ()
    """ Check code against inconsistent
        indentation (mixed spaced and tabs).
    """

    syntax_analysis_debug_output = ()

    """ Save debugging information to files
        when performing code syntax analysis.
    """

    show_ast_json = ()
    """ When work in console this option
        will show simplified version of AST
        generated by source code parser.
    """

    rewrite_from_ast = ()
    """ Debugging function tries to
        restore original code from
        generated AST.
    """
