using System;

namespace Axion.Core.Processing.Source {
    /// <summary>
    ///     Defines some settings for source code processing.
    /// </summary>
    [Flags]
    public enum SourceProcessingOptions {
        /// <summary>
        ///     Source is processed by default.
        /// </summary>
        None = 0,

        /// <summary>
        ///     Check code against inconsistent
        ///     indentation (mixed spaced and tabs).
        /// </summary>
        CheckIndentationConsistency = 1 << 0,

        /// <summary>
        ///     Save debugging information to files
        ///     when performing code syntax analysis.
        /// </summary>
        SyntaxAnalysisDebugOutput = 1 << 1,

        /// <summary>
        ///     When work in console, this option
        ///     will show minified version of AST,
        ///     generated by source code parser.
        /// </summary>
        ShowAstJson = 1 << 2,

        /// <summary>
        ///     Debugging function, tries to
        ///     restore original code from
        ///     generated AST.
        /// </summary>
        RewriteFromAst = 1 << 3
    }
}